services:
  backend:
    restart: no
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - "MONGO_USER=${DB_USER}"
      - "MONGO_PASSWORD=${DB_PASSWORD}"
      - "MONGO_URL=mongodb://${DB_USER}:${DB_PASSWORD}@mongo:27017/"
      - "UPLOAD_FOLDER=/app/datastore"
    volumes:
      - ./backend/datastore:/app/datastore


  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db:rw

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${DB_USER}:${DB_PASSWORD}@mongo:27017/
      ME_CONFIG_BASICAUTH: false
